# Generated by Django 5.0.6 on 2024-05-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_DB', '0003_remove_product_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
